[mypy]
# Enforce strict optional checking
strict_optional = True

# Other strict checks
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True

# Source code path
mypy_path = .

[mypy-tests.*]
# Tests can be more lenient with typing
disallow_untyped_defs = False
disallow_incomplete_defs = False
